// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ojuitmfclbzwrsxbchzr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9qdWl0bWZjbGJ6d3JzeGJjaHpyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTI5MTU2NDYsImV4cCI6MjA2ODQ5MTY0Nn0.-EjiUOBMmgvuset0QGxAxJjQfkPxZ7B5eUknwoUpg6k";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});